// AUTO-GENERATED! This file automagically generated with gen-api.js
// Neovim version: 0.2.0

export interface Api {
  uiAttach(width: number, height: number, options: object): void,
  uiDetach(): void,
  uiTryResize(width: number, height: number): void,
  uiSetOption(name: string, value: object): void,
  command(command: string): void,
  feedkeys(keys: string, mode: string, escape_csi: boolean): void,
  input(keys: string): number,
  replaceTermcodes(str: string, from_part: boolean, do_lt: boolean, special: boolean): string,
  commandOutput(str: string): string,
  eval(expr: string): object,
  callFunction(fname: string, args: any[]): object,
  strwidth(str: string): number,
  listRuntimePaths(): string[],
  setCurrentDir(dir: string): void,
  getCurrentLine(): string,
  setCurrentLine(line: string): void,
  delCurrentLine(): void,
  getVar(name: string): object,
  setVar(name: string, value: object): void,
  delVar(name: string): void,
  getVvar(name: string): object,
  getOption(name: string): object,
  setOption(name: string, value: object): void,
  outWrite(str: string): void,
  errWrite(str: string): void,
  errWriteln(str: string): void,
  listBufs(): Buffer[],
  getCurrentBuf(): Buffer,
  setCurrentBuf(buffer: Buffer): void,
  listWins(): Window[],
  getCurrentWin(): Window,
  setCurrentWin(window: Window): void,
  listTabpages(): Tabpage[],
  getCurrentTabpage(): Tabpage,
  setCurrentTabpage(tabpage: Tabpage): void,
  subscribe(event: string): void,
  unsubscribe(event: string): void,
  getColorByName(name: string): number,
  getColorMap(): object,
  getMode(): object,
  getApiInfo(): any[],
  callAtomic(calls: any[]): any[],
  buffer: Buffer,
  window: Window,
  tabpage: Tabpage,
}

export interface Buffer {
  lineCount(buffer: Buffer): number,
  getLines(buffer: Buffer, start: number, end: number, strict_indexing: boolean): string[],
  setLines(buffer: Buffer, start: number, end: number, strict_indexing: boolean, replacement: string[]): void,
  getVar(buffer: Buffer, name: string): object,
  getChangedtick(buffer: Buffer): number,
  setVar(buffer: Buffer, name: string, value: object): void,
  delVar(buffer: Buffer, name: string): void,
  getOption(buffer: Buffer, name: string): object,
  setOption(buffer: Buffer, name: string, value: object): void,
  getNumber(buffer: Buffer): number,
  getName(buffer: Buffer): string,
  setName(buffer: Buffer, name: string): void,
  isValid(buffer: Buffer): boolean,
  getMark(buffer: Buffer, name: string): number[],
  addHighlight(buffer: Buffer, src_id: number, hl_group: string, line: number, col_start: number, col_end: number): number,
  clearHighlight(buffer: Buffer, src_id: number, line_start: number, line_end: number): void,
}

export interface Window {
  getBuf(window: Window): Buffer,
  getCursor(window: Window): number[],
  setCursor(window: Window, pos: number[]): void,
  getHeight(window: Window): number,
  setHeight(window: Window, height: number): void,
  getWidth(window: Window): number,
  setWidth(window: Window, width: number): void,
  getVar(window: Window, name: string): object,
  setVar(window: Window, name: string, value: object): void,
  delVar(window: Window, name: string): void,
  getOption(window: Window, name: string): object,
  setOption(window: Window, name: string, value: object): void,
  getPosition(window: Window): number[],
  getTabpage(window: Window): Tabpage,
  getNumber(window: Window): number,
  isValid(window: Window): boolean,
}

export interface Tabpage {
  listWins(tabpage: Tabpage): Window[],
  getVar(tabpage: Tabpage, name: string): object,
  setVar(tabpage: Tabpage, name: string, value: object): void,
  delVar(tabpage: Tabpage, name: string): void,
  getWin(tabpage: Tabpage): Window,
  getNumber(tabpage: Tabpage): number,
  isValid(tabpage: Tabpage): boolean,
}

export const Prefixes = {
  Core: 'nvim_' ,
  Buffer: 'nvim_buf_',
  Window: 'nvim_win_',
  Tabpage: 'nvim_tabpage_',
}

export enum ExtType {
  Buffer,
  Window,
  Tabpage,
}
