// TODO: dynamic and async load?
import './files'
import './buffers'
import './explorer'
import './commands'
import './change-dir'
import './vim-create'
import './vim-rename'
import './vim-switch'
import './color-picker'
import './autocomplete'
import './tabline'
import './grep'
import './remote'
