const { src, same } = require('../util')

const window = src('vscode/window').default

describe('vscode api - window', () => {
  describe('var', () => {
    it('activeTextEditor')
    it('visibleTextEditors')
    it('state')
    it('terminals')
  })

  describe('events', () => {
    it('onDidChangeActiveTextEditor')
    it('onDidChangeVisibleTextEditors')
    it('onDidChangeTextEditorSelection')
    it('onDidChangeTextEditorVisibleRanges')
    it('onDidChangeTextEditorOptions')
    it('onDidChangeTextEditorViewColumn')
    it('onDidOpenTerminal')
    it('onDidCloseTerminal')
    it('onDidChangeWindowState')
  })

  describe('func', () => {
    it('createInputBox')
    it('createOutputChannel')
    it('createQuickPick')
    it('createStatusBarItem')
    it('createTerminal')
    it('createTextEditorDecorationType')
    it('createTreeView')
    it('createWebviewPanel')
    it('registerTreeDataProvider')
    it('registerUriHandler')
    it('registerWebviewPanelSerializer')
    it('setStatusBarMessage')
    it('showErrorMessage')
    it('showInformationMessage')
    it('showInputBox')
    it('showOpenDialog')
    it('showQuickPick')
    it('showSaveDialog')
    it('showTextDocument')
    it('showWarningMessage')
    it('showWorkspaceFolderPick')
    it('withProgress')
    it('withScmProgress')
  })
})
